apiVersion: v1
kind: Pod
metadata:
  name: building-apps-pod
  labels:
    app: kubeacademy
spec:
  containers:
  - name: building-apps-container
    image: scooterjec/kubeacademy-building-apps:0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8888
