apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: my-app
build:
  artifacts:
  - image: my-cool-app
    context: src
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
